name: Deploy React App to Tencent Cloud Server

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # 指定 Node.js 版本

      # Step 3: 安装依赖
      - name: Install dependencies
        run: npm install

      # Step 4: 构建 React 项目
      - name: Build React App
        run: npm run build

      # Step 5: 压缩 build 文件夹为 tar.gz 格式
      - name: Compress Build Folder
        run: tar -czf build.tar.gz build

      # Step 6: 连接到服务器并上传文件
      - name: Deploy to Tencent Cloud Server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.TENCENT_CVM_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build.tar.gz"  # 本地上传文件
          target: "${{ secrets.REMOTE_PATH }}"  # 上传到服务器上的目录

      # Step 7: 解压文件并部署到服务器目录
      - name: Extract and Deploy on Server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.TENCENT_CVM_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.REMOTE_PATH }}
            rm -rf build  # 删除旧的 build 文件夹
            tar -xzf build.tar.gz  # 解压新上传的文件
            rm -f build.tar.gz  # 删除压缩文件
            sudo systemctl restart nginx  # 重启 Nginx 服务以应用更改

      # Step 8: 检查部署状态
      - name: Check Deployment
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.TENCENT_CVM_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Deployment finished on ${{ secrets.TENCENT_CVM_IP }}"
            sudo systemctl status nginx
